package S2D.types

import org.lwjgl.glfw.GLFW.*

enum KeyCode(val value: Int):
  case Space extends KeyCode(GLFW_KEY_SPACE)
  case Apostrophe extends KeyCode(GLFW_KEY_APOSTROPHE)
  case Comma extends KeyCode(GLFW_KEY_COMMA)
  case Minus extends KeyCode(GLFW_KEY_MINUS)
  case Period extends KeyCode(GLFW_KEY_PERIOD)
  case Slash extends KeyCode(GLFW_KEY_SLASH)

  case Key0 extends KeyCode(GLFW_KEY_0)
  case Key1 extends KeyCode(GLFW_KEY_1)
  case Key2 extends KeyCode(GLFW_KEY_2)
  case Key3 extends KeyCode(GLFW_KEY_3)
  case Key4 extends KeyCode(GLFW_KEY_4)
  case Key5 extends KeyCode(GLFW_KEY_5)
  case Key6 extends KeyCode(GLFW_KEY_6)
  case Key7 extends KeyCode(GLFW_KEY_7)
  case Key8 extends KeyCode(GLFW_KEY_8)
  case Key9 extends KeyCode(GLFW_KEY_9)

  case A extends KeyCode(GLFW_KEY_A)
  case B extends KeyCode(GLFW_KEY_B)
  case C extends KeyCode(GLFW_KEY_C)
  case D extends KeyCode(GLFW_KEY_D)
  case E extends KeyCode(GLFW_KEY_E)
  case F extends KeyCode(GLFW_KEY_F)
  case G extends KeyCode(GLFW_KEY_G)
  case H extends KeyCode(GLFW_KEY_H)
  case I extends KeyCode(GLFW_KEY_I)
  case J extends KeyCode(GLFW_KEY_J)
  case K extends KeyCode(GLFW_KEY_K)
  case L extends KeyCode(GLFW_KEY_L)
  case M extends KeyCode(GLFW_KEY_M)
  case N extends KeyCode(GLFW_KEY_N)
  case O extends KeyCode(GLFW_KEY_O)
  case P extends KeyCode(GLFW_KEY_P)
  case Q extends KeyCode(GLFW_KEY_Q)
  case R extends KeyCode(GLFW_KEY_R)
  case S extends KeyCode(GLFW_KEY_S)
  case T extends KeyCode(GLFW_KEY_T)
  case U extends KeyCode(GLFW_KEY_U)
  case V extends KeyCode(GLFW_KEY_V)
  case W extends KeyCode(GLFW_KEY_W)
  case X extends KeyCode(GLFW_KEY_X)
  case Y extends KeyCode(GLFW_KEY_Y)
  case Z extends KeyCode(GLFW_KEY_Z)

  case Escape extends KeyCode(GLFW_KEY_ESCAPE)
  case Enter extends KeyCode(GLFW_KEY_ENTER)
  case Tab extends KeyCode(GLFW_KEY_TAB)
  case Backspace extends KeyCode(GLFW_KEY_BACKSPACE)
  case Insert extends KeyCode(GLFW_KEY_INSERT)
  case Delete extends KeyCode(GLFW_KEY_DELETE)

  case Right extends KeyCode(GLFW_KEY_RIGHT)
  case Left extends KeyCode(GLFW_KEY_LEFT)
  case Down extends KeyCode(GLFW_KEY_DOWN)
  case Up extends KeyCode(GLFW_KEY_UP)

  case F1 extends KeyCode(GLFW_KEY_F1)
  case F2 extends KeyCode(GLFW_KEY_F2)
  case F3 extends KeyCode(GLFW_KEY_F3)
  case F4 extends KeyCode(GLFW_KEY_F4)
  case F5 extends KeyCode(GLFW_KEY_F5)
  case F6 extends KeyCode(GLFW_KEY_F6)
  case F7 extends KeyCode(GLFW_KEY_F7)
  case F8 extends KeyCode(GLFW_KEY_F8)
  case F9 extends KeyCode(GLFW_KEY_F9)
  case F10 extends KeyCode(GLFW_KEY_F10)
  case F11 extends KeyCode(GLFW_KEY_F11)
  case F12 extends KeyCode(GLFW_KEY_F12)

  case LeftShift extends KeyCode(GLFW_KEY_LEFT_SHIFT)
  case LeftControl extends KeyCode(GLFW_KEY_LEFT_CONTROL)
  case LeftAlt extends KeyCode(GLFW_KEY_LEFT_ALT)
  case LeftSuper extends KeyCode(GLFW_KEY_LEFT_SUPER)
  case RightShift extends KeyCode(GLFW_KEY_RIGHT_SHIFT)
  case RightControl extends KeyCode(GLFW_KEY_RIGHT_CONTROL)
  case RightAlt extends KeyCode(GLFW_KEY_RIGHT_ALT)
  case RightSuper extends KeyCode(GLFW_KEY_RIGHT_SUPER)